class AddColumnsToUsers < ActiveRecord::Migration[5.1]
  def change
    # role can be company representative, Decision Maker, Validator, admin
    add_column :users, :role, :string
    # login_id generated by database given user in case of repeated email
    add_column :users, :login_id, :integer
    # whether approved by the admin
    add_column :users, :approved, :boolean, default: false
  end
end
